### ISSUE TITLE
`Error: $ operator is invalid for atomic vectors`

### ISSUE THREAD

**Issue by miguelmorin** [alan-turing-institute/PosteriorBootstrap#12]
The data in the branch `7-restructure-package` throws an error 

```
> out_bayes1 <- BayesLogit::logit(y=0.5*(dataset1$y_train+1), X=cbind(1,dataset1$x_train), P0=diag(rep(1/prior_variance,dataset1$n_cov+1) ), samp=n_s .... [TRUNCATED] 
[1] "y is a proportion; it must be <= 1."
Error: $ operator is invalid for atomic vectors
> traceback()
5: BayesLogit::logit(y = y, X = X, P0 = P0, samp = n_samp, burn = n_samp) at pcb_vb_classn_sb.R#224
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("~/Projects/PosteriorBootstrap/PosteriorBootstrap/R/pcb_vb_classn_sb.R", 
       echo = TRUE)
```

Scaling the `y` argument to be between 0 and 1 fixes the issue. I don't know if we can debug inside the `BayesLogit` dataset, otherwise we need to ask Simon for his original data.

**Comment by slllll** [comment]
We used the data from the Fernandez-Delgado reference in the paper (data: http://persoal.citius.usc.es/manuel.fernandez.delgado/papers/jmlr/data.tar.gz) (paper: http://jmlr.org/papers/v15/delgado14a.html)

As per BayesLogit package documentation the values of y should be 0 or 1.

**Comment by slllll** [comment]
I just checked; so the raw data we are using (statlog-german-credit package) has responses \in {-1,1}. If you don't see that using the linked data, let me know

**Comment by jemrobinson** [comment]
Hi @slllll , the data we're using is [here](https://github.com/alan-turing-institute/PosteriorBootstrap/blob/master/inst/extdata/statlog-german-credit.dat) which we took from [here](https://archive.ics.uci.edu/ml/datasets/statlog+(german+credit+data)).

If these two datasets are different, perhaps there's a simple transformation between them (such as the one we've added to the code here). I'm happy to use either dataset as the input, but if one is more "official" than the other, we should probably use that and transform it if needed.

@miguelmorin will look into this.

**Comment by miguelmorin** [comment]
I downloaded and extracted the data. I got:

```
$ load("~/Downloads/statlog-german-credit/statlog-german-credit_R.dat")
Error in load("~/Downloads/statlog-german-credit/statlog-german-credit_R.dat") : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘statlog-german-credit_R.dat’ has magic number '	f1	f'
  Use of save versions prior to 2 is deprecated 
```

But I could still read the data by other means, though I could not manipulate it in R. @slllll , the last column looks like it has values in (0, 1). But you do convert to (-1, 1) a few lines after reading in the data:

```
# Convert y to +/- 1 format
dataset$y <- 2 * raw_dataset[, dataset$n_cov + 1] - 1
```

So I think that the raw data should be in (0, 1). Please tell me if you disagree.

I scaled our data, read from a plaintext format, to have 0-mean and standard deviation 1 and it looks very similar (I checked a few numbers and the author's data is a rounding of ours, as they only have 5 digits after the period). See PR #31.
