### ISSUE TITLE
Robustify sample data

### ISSUE THREAD

**Issue by miguelmorin** [alan-turing-institute/PosteriorBootstrap#13]
- [ ] download data directly from [source](http://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data-numeric)
- [x] add test or assertion to ensure that outcome variable is between -1 and 1, instead of letting BayesLogit throw a cryptic error

**Comment by slllll** [comment]
By 'robustify sample data' do you mean the dataset outcomes should be an integer in {0,1}, I agree. Otherwise I don't understand what this refers to.

**Comment by miguelmorin** [comment]
@slllll Yes, that is what I mean. We were getting a cryptic error `$ is not valid for atomic types` due to the data fed to `BayesLogit` not being in {0, 1}.
