### ISSUE TITLE
Fix `Warning in eval(family$initialize) :   non-integer #successes in a binomial glm!`

### ISSUE THREAD

**Issue by miguelmorin** [alan-turing-institute/PosteriorBootstrap#16]
The first run throws this warning, even though all `y_all` in line 135 are in {0,1}.

The problem comes from the weights. We confirmed that the responses are all 0-1 and that the weights are non-integers. We can fix the warning by casting the weights as integers or by using quasi-binomial distribution instead of binomial.

The documentation of `glm.fit` mentions that weights have to be integers:

  > Non-NULL weights can be used to indicate that different observations have different dispersions (with the values in weights being inversely proportional to the dispersions); or equivalently, when the elements of weights are positive integers w_i, that each response y_i is the mean of w_i unit-weight observations. For a binomial GLM prior weights are used to give the number of trials when the response is the proportion of successes: they would rarely be used for a Poisson GLM.

I emailed Simon asking for clarifications.

**Comment by slllll** [comment]
The weights here refer to the contribution each observation makes to the weighted likelihood. The weights shouldn't be integers, they should be floats. This is a nonstandard use of the glm.fit function, but this is deliberate, as it achieves our posterior sampling using the well-established glm.fit R function. The warning should be suppressed.

**Comment by miguelmorin** [comment]
Yes, I thought that weights were those in the likelihood function. But then `glm.fit` should be accepting integers, but because of the binomial link function it expects them to be integers.

Packages with warnings are not accepted by CRAN, as mentioned in the [R packages book](https://r-pkgs.org/release.html)

> You must fix all ERRORs and WARNINGs. A package that contains any errors or warnings will not be accepted by CRAN.

One way to proceed is to scale all weights by 1 million, for example, and cast them as integers.

How would you like to proceed?

**Comment by slllll** [comment]
What do you mean exactly by 'keep the quasi-binomial link function'? 

I think we just want to reproduce the underlying fitting routine of glm.fit, but removing this warning. There are probably other efficiencies that can be saved this way, as we just want the coefficient estimates from the glm.fit routine, and none of the other quantities that are computed by this function.

**Comment by miguelmorin** [comment]
I mean that we use `quasibinomial` in this snippet of `glm.fit`:

```
glm_fit <- stats::glm.fit(x = cbind(1, x_all),
                              y = y_all,
                              weights = wgts,
                              family = stats::quasibinomial(link = "logit"))
```

Yes, we want to reproduce the fitting routine but cannot have the warning. Quasibinomial was the way James Robinson found to do that.

**Comment by miguelmorin** [comment]
See [this thread](https://stackoverflow.com/questions/12953045/warning-non-integer-successes-in-a-binomial-glm-survey-packages):

> The quasibinomial and binomial families use exactly the same numerical method, ie IRLS with appropriately chosen mu and eta. The differences are that quasibinomial 1) suppresses the integer check, and 2) doesn't report an AIC, since it's technically not maximum likelihood-based.

> You can check for yourself that quasibinomial is no more robust than binomial, just by generating random data and fitting models with the 2 families. You should find that, regardless of what the data is like or how close you are to linearly separable classes, the model estimates are exactly the same.

I added an answer myself:

Quasi-binomial in R for `glm.fit` is exactly the same as `binomial` (as
mentioned in a comment by @HongOoi). A diff on the
source code of `stats::binomial` and `stats::quasibinomial` shows the following changes:

- the text "binomial" becomes "quasibinomial"
- the aic function returns NA instead of the calculated AIC

and the following removals:

- setting outcomes to 0 when weights = 0
- check on integrality of weights
- `simfun` function to simulate data

Only `simfun` could make a difference, but the source code of `glm.fit` shows no use of that function, unlike other fields in the object returned by `stats::binomial` such as `mu.eta` and `link`.

In addition, I checked that the results from using `quasibinomial` or `binomial` are the same in this minimal working example::



    library('MASS')
    library('stats')
    
    gen_data <- function(n=100, p=3) {
    
      set.seed(1)  
      weights <- stats::rgamma(n=n, shape=rep(1, n), rate=rep(1, n))
      y <- stats::rbinom(n=n, size=1, prob=0.5)
      theta <- stats::rnorm(n=p, mean=0, sd=1)
      means <- colMeans(as.matrix(y) %*% theta)
      x <- MASS::mvrnorm(n=n, means, diag(1, p, p))
      
      return(list(x=x, y=y, weights=weights, theta=theta))  
    }
    
    get_theta <- function(family) {
      data <- gen_data()
      fit <- stats::glm.fit(x = data$x,
                            y = data$y,
                            weights = data$weights,
                            family = family)
      return(fit$coefficients)
    }
    
    theta1 <- get_theta(family=stats::binomial(link = "logit"))
    theta2 <- get_theta(family=stats::quasibinomial(link = "logit"))
      
    all(theta1 == theta2)
    [1] TRUE

[This
thread](https://stats.stackexchange.com/questions/91724/what-is-quasi-binomial-distribution-in-the-context-of-glm) suggests that the quasibinomial distribution is different from the binomial distribution with an additional parameter `phi`. It may apply in statistics but not in R, as you can see. In addition, no place in the source code of `quasibinomial` mentions that additional `phi` parameter.

I cannot add it as a test because the warning would still show up on CRAN. So I created branch `16-verify-quasibinomial`. You can call it with 

```
library(PosteriorBootstrap)
PosteriorBootstrap::verify_quasibionmial()
```

Therefore, I vote to keep quasibinomial and to close this issue.
