### ISSUE TITLE
Code linting and style

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/PosteriorBootstrap#28]
We should enforce a consistent style on the codebase. The easiest way to do so is using [lintr](https://github.com/jimhester/lintr#continuous-integration). If we go down this route, we should decide whether failing the style should cause a failing test, a warning in the form of comments from the lintr-bot or both.

**Comment by miguelmorin** [comment]
In the process of fixing the code to pass the linter, I also removed commented code from the plot

```
#out_VB1 <- logit_VB(dataset1, prior_mean = 0, prior_cov = prior_variance, n_samp = n_samp)
...
  #plot_df1 <- rbind(plot_df1, tibble::tibble(id = 1:n_samp, beta3 = out_VB1$beta[, 3], beta5 = out_VB1$beta[, 5], beta21 = out_VB1$beta[, 21], beta22 = out_VB1$beta[, 22], Method = "VB", prior_sample_size = i) )
...
#ylim(-0.75, 1.6) +
  #xlim(0, 1.2) +
  #theme(panel.spacing = unit(1, "lines"), plot.margin = margin(1, 10, 0, 10, "pt"), legend.position = "none" )
```

We will also need to remove these lines, whose variables are unused. This is the only linter issue left:

```
w_raw_data <- stats::rexp(n = dataset$n)
w_data <- w_raw_data / sum(w_raw_data) * (1 - v1)
```
