### ISSUE TITLE
Bayes Logistic regression in Stan

### ISSUE THREAD

**Issue by miguelmorin** [alan-turing-institute/PosteriorBootstrap#38]
We can sidestep the BayesLogit and PolyaGamma issue by doing Bayesian Logistic regression on Stan.

**Comment by jemrobinson** [comment]
... but I think this will require a restructuring of the project to be based on the [`rstantools` skeleton](https://mc-stan.org/rstantools/)

**Comment by miguelmorin** [comment]
I understood from our meeting on Thursday that outside of the case of `c = 0`, we need samples from RStan to perform the non-parametric learning update. So I think we (or I) have to do this.

**Comment by miguelmorin** [comment]
Simon provided a link to an RStan logistic regression:

> Sorry, I don’t have [a piece of code with the Stan model that replaces the use of BayesLogit] to hand. How about https://github.com/danilofreire/r-scripts/blob/master/stan-logistic-regression.R
